// K-WorkBridge 공통 언어 시스템
const LANGS = {
  ko: {
    // 네비게이션
    nav_home: '홈', nav_community: '커뮤니티', nav_education: '직무교육',
    nav_internship: '인턴십', nav_login: '로그인', nav_start: '무료로 시작하기',

    // 공통
    free: '무료', apply: '신청하기', detail: '자세히 보기 →', all: '전체',
    new_post: '✏️ 글쓰기', search_placeholder: '검색어를 입력하세요',
    submit: '등록하기', cancel: '취소', latest: '최신순', views_sort: '조회순',

    // 홈 히어로
    hero_badge: '다문화 청년을 위한 취업 플랫폼',
    hero_h1_1: '커뮤니티에서', hero_h1_2: '커리어까지',
    hero_sub: '국내 다문화 청년의 취업을 잇다',
    hero_desc: 'K-WorkBridge는 국내 거주 다문화 가정 청년 대학생을 위한 커뮤니티 기반 인턴십 매칭 및 직무 교육 통합 플랫폼입니다. 함께 성장하고, 함께 취업하세요.',
    hero_btn1: '지금 시작하기', hero_btn2: '서비스 알아보기',
    stat1_num: '3단계', stat1_label: '체계적인 취업 여정',
    stat2_num: '5개', stat2_label: '지원 언어',
    stat3_num: '100%', stat3_label: '무료 서비스',

    // 홈 플로우 카드
    flow1_title: '커뮤니티 활동', flow1_desc: '같은 배경을 가진 청년들과 네트워크를 형성하고, 정보를 공유하며 함께 성장합니다.',
    flow2_title: '직무 교육', flow2_desc: '실무 중심의 직무 교육으로 취업에 필요한 역량을 체계적으로 쌓습니다.',
    flow3_title: '인턴십 매칭', flow3_desc: 'AI 기반 매칭 시스템으로 나에게 맞는 인턴십 기회를 연결해 드립니다.',

    // 홈 features
    feat_label: '핵심 기능', feat_title: '취업을 위한 모든 것을<br>한 곳에서',
    feat1_title: '커뮤니티 네트워킹', feat1_desc: '다문화 청년들이 서로 연결되고 경험을 공유할 수 있는 안전한 커뮤니티 공간을 제공합니다.',
    feat2_title: '맞춤형 직무 교육', feat2_desc: 'IT, 마케팅, 경영 등 다양한 분야의 실무 교육 과정을 5개 언어로 제공합니다.',
    feat3_title: 'AI 인턴십 매칭', feat3_desc: '개인의 역량과 관심사를 분석하여 최적의 인턴십 기회를 자동으로 매칭해 드립니다.',
    feat4_title: '5개 언어 지원', feat4_desc: '한국어, 영어, 중국어, 일본어, 베트남어로 모든 서비스를 이용할 수 있습니다.',
    feat5_title: '이력서 & 포트폴리오', feat5_desc: '전문가 템플릿으로 한국형 이력서와 포트폴리오를 쉽게 만들 수 있습니다.',
    feat6_title: '기업 파트너십', feat6_desc: '다양성을 중시하는 국내 기업들과 협력하여 실질적인 취업 기회를 제공합니다.',

    // 홈 how
    how_label: '이용 방법', how_title: '3단계로 취업을 완성하세요',
    how1_title: '커뮤니티 참여', how1_desc: '회원가입 후 같은 배경을 가진 청년들과 연결되세요. 스터디 그룹, 멘토링, 정보 공유 등 다양한 활동에 참여할 수 있습니다.',
    how2_title: '직무 역량 강화', how2_desc: 'IT, 마케팅, 경영 분석 등 다양한 직무 교육을 수강하세요. 모든 강의는 모국어로 제공되어 학습 장벽을 낮춥니다.',
    how3_title: '인턴십 매칭', how3_desc: '교육 수료 후 AI가 당신의 역량에 맞는 인턴십을 추천합니다. 다양성을 존중하는 기업들과 연결되어 실제 커리어를 시작하세요.',

    // 홈 CTA
    cta_label: '지금 바로 시작하세요',
    cta_title: '당신의 커리어를<br>K-WorkBridge와 함께',
    cta_desc: '무료로 가입하고 커뮤니티부터 시작하세요. 함께라면 더 빨리, 더 멀리 갈 수 있습니다.',
    cta_btn1: '무료로 시작하기', cta_btn2: '기업 파트너 문의',

    // 언어 섹션
    lang_title: '당신의 언어로 시작하세요',
    lang_desc: '언어는 장벽이 되어서는 안 됩니다. K-WorkBridge는 5개 언어로 동일한 품질의 서비스를 제공합니다.',

    // 푸터
    footer_desc: '국내 다문화 가정 청년 대학생을 위한 커뮤니티 기반 인턴십 매칭 및 직무 교육 통합 플랫폼',
    footer_service: '서비스', footer_support: '지원', footer_company: '회사',
    footer_community: '커뮤니티', footer_education: '직무 교육', footer_internship: '인턴십 매칭',
    footer_faq: '자주 묻는 질문', footer_help: '고객센터', footer_notice: '공지사항',
    footer_about: '소개', footer_partner: '기업 파트너십', footer_privacy: '개인정보처리방침',
    footer_copy: '다문화 청년의 더 나은 내일을 위해',

    // 게시판
    board_title: '커뮤니티', board_desc: '다문화 청년들이 함께 소통하고 정보를 나누는 공간입니다',
    tab_all: '전체', tab_notice: '📢 공지사항', tab_community: '🤝 커뮤니티',
    tab_job: '💼 취업정보', tab_qna: '❓ Q&A',
    list_num: '번호', list_title: '제목', list_author: '작성자', list_date: '날짜', list_views: '조회',
    sort_latest: '최신순', sort_views: '조회순', sort_popular: '인기순',
    write_title: '✏️ 글쓰기', write_category: '게시판 선택', write_input_title: '제목',
    write_content: '내용', write_tag: '태그 (선택)', write_tag_placeholder: '예: #인턴십 #취업 (쉼표로 구분)',
    write_placeholder: '내용을 입력하세요. 서로를 존중하는 따뜻한 커뮤니티를 만들어요 😊',
    cat_notice: '공지', cat_community: '커뮤니티', cat_job: '취업정보', cat_qna: 'Q&A',
    side_latest: '최신 공지사항', side_popular: '인기 게시글', side_tags: '인기 태그',
    toast_submitted: '게시글이 등록되었습니다! 🎉',
    toast_title_required: '제목을 입력해주세요!', toast_content_required: '내용을 입력해주세요!',
    no_posts: '게시글이 없습니다',
    cat_community_opt: '🤝 커뮤니티', cat_job_opt: '💼 취업정보', cat_qna_opt: '❓ Q&A',

    // 직무교육
    edu_notice: '2026년 고용노동부 「미래내일 일경험 지원사업」 참여자 모집 중 — 무료 직무교육 + 인턴십 연계',
    edu_title: '직무교육', edu_desc: '실무 중심의 교육으로 취업 역량을 키우세요. 국비지원 과정부터 자체 무료 강의까지 5개 언어로 제공합니다.',
    edu_stat1: '48개 강의', edu_stat2: '6개 직무 분야', edu_stat3: '무료', edu_stat4: '5개 지원 언어',
    edu_filter_all: '전체', edu_filter_it: '💻 IT·개발', edu_filter_mkt: '📣 마케팅',
    edu_filter_biz: '💼 경영·회계', edu_filter_data: '📊 데이터분석',
    edu_filter_lang: '🗣️ 한국어', edu_filter_design: '🎨 디자인',
    edu_filter_beginner: '입문', edu_filter_intermediate: '중급',
    edu_gov_title: '🏛️ 2026년 정부 지원 취업 프로그램',
    edu_gov_desc: '고용노동부·서울시 등 공공기관과 협력하여 실질적인 취업 지원을 제공합니다. 아래 프로그램은 모두 무료로 참여 가능합니다.',
    edu_gov_btn: '신청하기',
    edu_featured: '🌟 추천 강의', edu_all_courses: '📚 전체 강의', edu_reviews: '💬 수료생 후기',
    edu_enroll: '수강 신청', edu_hours: '총 24시간', edu_enrolled: '수강 신청이 완료되었습니다! 🎉',

    // 인턴십
    intern_notice: '2026년 제1기 고용노동부 「청년일경험 지원사업(인턴형)」 — 참여기업 모집 마감 D-3',
    intern_title: '인턴십 매칭', intern_desc: 'AI가 나의 역량과 관심사를 분석해 최적의 인턴십을 추천합니다. 다양성을 존중하는 기업들과 연결되세요.',
    intern_stat1: '124개 진행 중인 공고', intern_stat2: '38개 파트너 기업',
    intern_stat3: '89% 취업 연계율', intern_stat4: '월 200만원 평균 급여',
    intern_ai_label: '✦ AI 매칭 시스템',
    intern_ai_title: '나에게 딱 맞는 인턴십을 AI가 찾아드립니다',
    intern_ai_desc: '직무 교육 수료 이력, 관심 분야, 언어 능력, 거주 지역을 분석해 최적의 인턴십 공고를 매칭합니다.',
    intern_ai_btn: 'AI 매칭 시작하기',
    intern_ai_toast: 'AI 매칭을 시작합니다! 잠시 후 결과를 보내드립니다 🤖',
    intern_jobs: '📋 인턴십 공고', intern_process: '📌 지원 절차', intern_success: '🏆 합격 후기',
    intern_apply: '지원하기', intern_applied: '인턴십에 지원했습니다! 🎉',
    process1_title: '프로필 완성', process1_desc: '관심 직무, 언어 능력, 교육 수료 이력 등 프로필을 작성합니다',
    process2_title: 'AI 매칭', process2_desc: 'AI가 나의 역량에 맞는 인턴십 공고를 자동으로 추천합니다',
    process3_title: '간편 지원', process3_desc: '원클릭으로 지원서를 제출하고 기업의 연락을 기다립니다',
    process4_title: '합격 & 시작', process4_desc: '면접 준비부터 합격 후 입사까지 K-WorkBridge가 함께합니다',
  },

  en: {
    nav_home: 'Home', nav_community: 'Community', nav_education: 'Training',
    nav_internship: 'Internship', nav_login: 'Login', nav_start: 'Get Started Free',
    free: 'Free', apply: 'Apply', detail: 'Learn more →', all: 'All',
    new_post: '✏️ Write', search_placeholder: 'Search...',
    submit: 'Submit', cancel: 'Cancel', latest: 'Latest', views_sort: 'Most Viewed',
    hero_badge: 'Career Platform for Multicultural Youth',
    hero_h1_1: 'From Community', hero_h1_2: 'to Career',
    hero_sub: 'Bridging multicultural youth to Korean careers',
    hero_desc: 'K-WorkBridge is a community-based internship matching and job training platform for multicultural university students in Korea. Grow together, succeed together.',
    hero_btn1: 'Start Now', hero_btn2: 'Learn More',
    stat1_num: '3 Steps', stat1_label: 'Structured career journey',
    stat2_num: '5', stat2_label: 'Supported languages',
    stat3_num: '100%', stat3_label: 'Free service',
    flow1_title: 'Community Activity', flow1_desc: 'Build networks with peers who share similar backgrounds, share information and grow together.',
    flow2_title: 'Job Training', flow2_desc: 'Build skills needed for employment through practical, work-focused training programs.',
    flow3_title: 'Internship Matching', flow3_desc: 'Our AI-powered matching system connects you with internship opportunities that fit your profile.',
    feat_label: 'Key Features', feat_title: 'Everything for your career<br>in one place',
    feat1_title: 'Community Networking', feat1_desc: 'A safe community space where multicultural youth can connect and share experiences.',
    feat2_title: 'Customized Job Training', feat2_desc: 'Practical training courses in IT, marketing, management and more, available in 5 languages.',
    feat3_title: 'AI Internship Matching', feat3_desc: 'Automatically matches you with the best internship opportunities based on your skills and interests.',
    feat4_title: '5 Language Support', feat4_desc: 'All services available in Korean, English, Chinese, Japanese, and Vietnamese.',
    feat5_title: 'Resume & Portfolio', feat5_desc: 'Easily create Korean-style resumes and portfolios using professional templates.',
    feat6_title: 'Corporate Partnership', feat6_desc: 'Partnering with diversity-focused Korean companies to provide real employment opportunities.',
    how_label: 'How It Works', how_title: 'Complete your career in 3 steps',
    how1_title: 'Join Community', how1_desc: 'After signing up, connect with youth who share similar backgrounds. Join study groups, mentoring sessions, and information sharing.',
    how2_title: 'Build Job Skills', how2_desc: 'Take courses in IT, marketing, business analysis and more. All lectures are available in your native language.',
    how3_title: 'Internship Match', how3_desc: 'After completing training, AI recommends internships matching your skills. Connect with diversity-embracing companies.',
    cta_label: 'Get Started Today',
    cta_title: 'Your career journey<br>with K-WorkBridge',
    cta_desc: 'Sign up for free and start with the community. Together, we go faster and further.',
    cta_btn1: 'Start for Free', cta_btn2: 'Corporate Inquiry',
    lang_title: 'Start in your language',
    lang_desc: 'Language should never be a barrier. K-WorkBridge provides the same quality service in 5 languages.',
    footer_desc: 'Community-based internship matching and job training platform for multicultural university students in Korea',
    footer_service: 'Services', footer_support: 'Support', footer_company: 'Company',
    footer_community: 'Community', footer_education: 'Job Training', footer_internship: 'Internship',
    footer_faq: 'FAQ', footer_help: 'Help Center', footer_notice: 'Notice',
    footer_about: 'About', footer_partner: 'Partnership', footer_privacy: 'Privacy Policy',
    footer_copy: 'For a better tomorrow for multicultural youth',
    board_title: 'Community', board_desc: 'A space where multicultural youth communicate and share information.',
    tab_all: 'All', tab_notice: '📢 Notice', tab_community: '🤝 Community',
    tab_job: '💼 Job Info', tab_qna: '❓ Q&A',
    list_num: '#', list_title: 'Title', list_author: 'Author', list_date: 'Date', list_views: 'Views',
    sort_latest: 'Latest', sort_views: 'Most Viewed', sort_popular: 'Popular',
    write_title: '✏️ Write Post', write_category: 'Select Board', write_input_title: 'Title',
    write_content: 'Content', write_tag: 'Tags (optional)', write_tag_placeholder: 'e.g. #internship #job',
    write_placeholder: 'Write your post. Let\'s build a warm community that respects each other 😊',
    cat_notice: 'Notice', cat_community: 'Community', cat_job: 'Job Info', cat_qna: 'Q&A',
    side_latest: 'Latest Notices', side_popular: 'Popular Posts', side_tags: 'Popular Tags',
    toast_submitted: 'Post submitted successfully! 🎉',
    toast_title_required: 'Please enter a title!', toast_content_required: 'Please enter content!',
    no_posts: 'No posts found',
    cat_community_opt: '🤝 Community', cat_job_opt: '💼 Job Info', cat_qna_opt: '❓ Q&A',
    edu_notice: '2026 Ministry of Employment「Future Tomorrow Work Experience」 – Now Recruiting Participants',
    edu_title: 'Job Training', edu_desc: 'Build your career skills with practical training. From government-funded courses to free in-house programs, available in 5 languages.',
    edu_stat1: '48 Courses', edu_stat2: '6 Fields', edu_stat3: 'Free', edu_stat4: '5 Languages',
    edu_filter_all: 'All', edu_filter_it: '💻 IT·Dev', edu_filter_mkt: '📣 Marketing',
    edu_filter_biz: '💼 Business', edu_filter_data: '📊 Data Analytics',
    edu_filter_lang: '🗣️ Korean', edu_filter_design: '🎨 Design',
    edu_filter_beginner: 'Beginner', edu_filter_intermediate: 'Intermediate',
    edu_gov_title: '🏛️ 2026 Government-Supported Employment Programs',
    edu_gov_desc: 'We partner with public institutions including the Ministry of Employment and Seoul Metropolitan Government. All programs below are free.',
    edu_gov_btn: 'Apply Now',
    edu_featured: '🌟 Featured Courses', edu_all_courses: '📚 All Courses', edu_reviews: '💬 Reviews',
    edu_enroll: 'Enroll Now', edu_hours: '24 hours total', edu_enrolled: 'Successfully enrolled! 🎉',
    intern_notice: '2026 Ministry of Employment「Youth Work Experience (Intern)」– Company Applications Close in D-3',
    intern_title: 'Internship Matching', intern_desc: 'AI analyzes your skills and interests to recommend the best internship for you.',
    intern_stat1: '124 Active Listings', intern_stat2: '38 Partner Companies',
    intern_stat3: '89% Employment Rate', intern_stat4: 'Avg. ₩2M/month',
    intern_ai_label: '✦ AI Matching System',
    intern_ai_title: 'AI finds the perfect internship for you',
    intern_ai_desc: 'We analyze your training history, interests, language skills, and location to match you with the best internship listings.',
    intern_ai_btn: 'Start AI Matching',
    intern_ai_toast: 'Starting AI matching! Results will be sent shortly 🤖',
    intern_jobs: '📋 Internship Listings', intern_process: '📌 Application Process', intern_success: '🏆 Success Stories',
    intern_apply: 'Apply', intern_applied: 'Application submitted! 🎉',
    process1_title: 'Complete Profile', process1_desc: 'Fill in your interests, language skills, and training history',
    process2_title: 'AI Matching', process2_desc: 'AI automatically recommends internships that match your skills',
    process3_title: 'Easy Apply', process3_desc: 'Submit your application with one click and wait to hear back',
    process4_title: 'Get Hired!', process4_desc: 'K-WorkBridge supports you from interview prep to your first day',
  },

  zh: {
    nav_home: '首页', nav_community: '社区', nav_education: '职业培训',
    nav_internship: '实习匹配', nav_login: '登录', nav_start: '免费开始',
    free: '免费', apply: '申请', detail: '了解更多 →', all: '全部',
    new_post: '✏️ 发帖', search_placeholder: '请输入搜索词',
    submit: '提交', cancel: '取消', latest: '最新', views_sort: '最多浏览',
    hero_badge: '面向多文化青年的就业平台',
    hero_h1_1: '从社区', hero_h1_2: '到职业',
    hero_sub: '连接国内多文化青年的就业之路',
    hero_desc: 'K-WorkBridge是面向在韩多文化家庭大学生的社区型实习匹配和职业培训综合平台。共同成长，共同就业。',
    hero_btn1: '立即开始', hero_btn2: '了解服务',
    stat1_num: '3个步骤', stat1_label: '系统化就业旅程',
    stat2_num: '5种', stat2_label: '支持语言',
    stat3_num: '100%', stat3_label: '免费服务',
    flow1_title: '社区活动', flow1_desc: '与有相似背景的青年建立网络，分享信息，共同成长。',
    flow2_title: '职业培训', flow2_desc: '通过以实践为中心的职业培训，系统地积累就业所需能力。',
    flow3_title: '实习匹配', flow3_desc: '通过AI匹配系统，为您推荐最适合的实习机会。',
    feat_label: '核心功能', feat_title: '一站式就业服务',
    feat1_title: '社区网络', feat1_desc: '为多文化青年提供安全的社区空间，相互连接并分享经验。',
    feat2_title: '定制职业培训', feat2_desc: '提供IT、营销、管理等多个领域的实践培训，支持5种语言。',
    feat3_title: 'AI实习匹配', feat3_desc: '分析个人能力和兴趣，自动匹配最佳实习机会。',
    feat4_title: '5种语言支持', feat4_desc: '所有服务支持韩语、英语、中文、日语和越南语。',
    feat5_title: '简历与作品集', feat5_desc: '使用专业模板轻松制作韩式简历和作品集。',
    feat6_title: '企业合作', feat6_desc: '与重视多样性的国内企业合作，提供实质性的就业机会。',
    how_label: '使用方法', how_title: '三步完成就业',
    how1_title: '加入社区', how1_desc: '注册后与有相似背景的青年建立联系。参与学习小组、导师计划和信息分享活动。',
    how2_title: '提升职业能力', how2_desc: '参加IT、营销、经营分析等多种职业培训课程。所有课程均以母语提供。',
    how3_title: '实习匹配', how3_desc: '完成培训后，AI根据您的能力推荐实习机会。与尊重多样性的企业建立联系。',
    cta_label: '立即开始', cta_title: '与K-WorkBridge<br>共创您的职业生涯',
    cta_desc: '免费注册，从社区开始。团结就是力量，共同前进。',
    cta_btn1: '免费开始', cta_btn2: '企业合作咨询',
    lang_title: '用您的语言开始', lang_desc: '语言不应该成为障碍。K-WorkBridge提供5种语言的同等质量服务。',
    footer_desc: '面向韩国多文化家庭大学生的社区型实习匹配和职业培训综合平台',
    footer_service: '服务', footer_support: '支持', footer_company: '公司',
    footer_community: '社区', footer_education: '职业培训', footer_internship: '实习匹配',
    footer_faq: '常见问题', footer_help: '客服中心', footer_notice: '公告',
    footer_about: '关于我们', footer_partner: '企业合作', footer_privacy: '隐私政策',
    footer_copy: '为多文化青年创造更美好的明天',
    board_title: '社区', board_desc: '多文化青年相互交流和分享信息的空间。',
    tab_all: '全部', tab_notice: '📢 公告', tab_community: '🤝 社区',
    tab_job: '💼 就业信息', tab_qna: '❓ 问答',
    list_num: '编号', list_title: '标题', list_author: '作者', list_date: '日期', list_views: '浏览',
    sort_latest: '最新', sort_views: '最多浏览', sort_popular: '最热门',
    write_title: '✏️ 发帖', write_category: '选择版块', write_input_title: '标题',
    write_content: '内容', write_tag: '标签（选填）', write_tag_placeholder: '例: #实习 #就业',
    write_placeholder: '请输入内容。让我们共同打造温暖的社区 😊',
    cat_notice: '公告', cat_community: '社区', cat_job: '就业信息', cat_qna: '问答',
    side_latest: '最新公告', side_popular: '热门帖子', side_tags: '热门标签',
    toast_submitted: '帖子发布成功！🎉',
    toast_title_required: '请输入标题！', toast_content_required: '请输入内容！',
    no_posts: '没有帖子',
    cat_community_opt: '🤝 社区', cat_job_opt: '💼 就业信息', cat_qna_opt: '❓ 问答',
    edu_notice: '2026年韩国就业劳动部「未来明日工作经验支援事业」正在招募参与者',
    edu_title: '职业培训', edu_desc: '通过实践培训提升您的就业能力。从国家资助课程到免费内部讲座，提供5种语言。',
    edu_stat1: '48门课程', edu_stat2: '6个领域', edu_stat3: '免费', edu_stat4: '5种语言',
    edu_filter_all: '全部', edu_filter_it: '💻 IT·开发', edu_filter_mkt: '📣 市场营销',
    edu_filter_biz: '💼 经营·会计', edu_filter_data: '📊 数据分析',
    edu_filter_lang: '🗣️ 韩语', edu_filter_design: '🎨 设计',
    edu_filter_beginner: '入门', edu_filter_intermediate: '中级',
    edu_gov_title: '🏛️ 2026年政府支援就业项目',
    edu_gov_desc: '与就业劳动部、首尔市等公共机构合作，提供实质性就业支援。以下所有项目均可免费参与。',
    edu_gov_btn: '立即申请',
    edu_featured: '🌟 推荐课程', edu_all_courses: '📚 全部课程', edu_reviews: '💬 学员评价',
    edu_enroll: '报名', edu_hours: '共24小时', edu_enrolled: '报名成功！🎉',
    intern_notice: '2026年第1期就业劳动部「青年工作经验支援事业（实习型）」— 参与企业招募截止 D-3',
    intern_title: '实习匹配', intern_desc: 'AI分析您的能力和兴趣，为您推荐最优实习机会。与尊重多样性的企业建立联系。',
    intern_stat1: '124条招募中', intern_stat2: '38家合作企业',
    intern_stat3: '89%就业联系率', intern_stat4: '月均200万韩元',
    intern_ai_label: '✦ AI匹配系统',
    intern_ai_title: 'AI为您找到最合适的实习',
    intern_ai_desc: '分析您的培训记录、兴趣领域、语言能力和居住地区，匹配最优实习公告。',
    intern_ai_btn: '开始AI匹配',
    intern_ai_toast: 'AI匹配开始！稍后将发送结果 🤖',
    intern_jobs: '📋 实习公告', intern_process: '📌 申请流程', intern_success: '🏆 录取心得',
    intern_apply: '申请', intern_applied: '申请已提交！🎉',
    process1_title: '完善资料', process1_desc: '填写您的兴趣职务、语言能力和培训记录',
    process2_title: 'AI匹配', process2_desc: 'AI自动推荐与您能力匹配的实习公告',
    process3_title: '一键申请', process3_desc: '一键提交申请，等待企业联系',
    process4_title: '录取&入职', process4_desc: '从面试准备到入职，K-WorkBridge全程陪伴',
  },

  ja: {
    nav_home: 'ホーム', nav_community: 'コミュニティ', nav_education: '職務教育',
    nav_internship: 'インターンシップ', nav_login: 'ログイン', nav_start: '無料で始める',
    free: '無料', apply: '申し込む', detail: '詳しく見る →', all: 'すべて',
    new_post: '✏️ 投稿する', search_placeholder: '検索キーワードを入力',
    submit: '投稿する', cancel: 'キャンセル', latest: '新着順', views_sort: '閲覧数順',
    hero_badge: '多文化青年のためのキャリアプラットフォーム',
    hero_h1_1: 'コミュニティから', hero_h1_2: 'キャリアへ',
    hero_sub: '国内多文化青年の就職をつなぐ',
    hero_desc: 'K-WorkBridgeは、国内在住の多文化家庭の大学生向けコミュニティ型インターンシップマッチング・職務教育統合プラットフォームです。共に成長し、共に就職しましょう。',
    hero_btn1: '今すぐ始める', hero_btn2: 'サービスを見る',
    stat1_num: '3ステップ', stat1_label: '体系的な就職の旅',
    stat2_num: '5言語', stat2_label: '対応言語',
    stat3_num: '100%', stat3_label: '無料サービス',
    flow1_title: 'コミュニティ活動', flow1_desc: '同じ背景を持つ仲間とネットワークを築き、情報を共有して共に成長します。',
    flow2_title: '職務教育', flow2_desc: '実務中心の職務教育で、就職に必要な能力を体系的に積み上げます。',
    flow3_title: 'インターンシップマッチング', flow3_desc: 'AIマッチングシステムで、あなたに合ったインターンシップの機会を繋ぎます。',
    feat_label: '主な機能', feat_title: '就職のすべてを<br>一か所で',
    feat1_title: 'コミュニティネットワーキング', feat1_desc: '多文化青年が繋がり、経験を共有できる安全なコミュニティスペース。',
    feat2_title: 'カスタマイズ職務教育', feat2_desc: 'IT、マーケティング、経営など多様な分野の実務教育を5言語で提供します。',
    feat3_title: 'AIインターンシップマッチング', feat3_desc: '個人の能力と関心を分析し、最適なインターンシップを自動マッチングします。',
    feat4_title: '5言語対応', feat4_desc: '韓国語、英語、中国語、日本語、ベトナム語でサービスをご利用いただけます。',
    feat5_title: '履歴書＆ポートフォリオ', feat5_desc: 'プロ用テンプレートで韓国式履歴書とポートフォリオを簡単に作成できます。',
    feat6_title: '企業パートナーシップ', feat6_desc: '多様性を重視する国内企業と協力し、実質的な就職機会を提供します。',
    how_label: '使い方', how_title: '3ステップで就職を完成させる',
    how1_title: 'コミュニティ参加', how1_desc: '会員登録後、同じ背景を持つ仲間と繋がりましょう。スタディグループ、メンタリング、情報共有など様々な活動に参加できます。',
    how2_title: '職務能力強化', how2_desc: 'IT、マーケティング、経営分析などの職務教育を受講してください。全ての講義は母国語で提供されます。',
    how3_title: 'インターンシップマッチ', how3_desc: '教育修了後、AIがあなたの能力に合ったインターンシップを推薦します。',
    cta_label: '今すぐ始めましょう', cta_title: 'あなたのキャリアを<br>K-WorkBridgeと共に',
    cta_desc: '無料で登録して、コミュニティから始めましょう。一緒ならもっと速く、もっと遠くへ。',
    cta_btn1: '無料で始める', cta_btn2: '企業パートナー問い合わせ',
    lang_title: 'あなたの言語で始めましょう', lang_desc: '言語が障壁になるべきではありません。K-WorkBridgeは5言語で同じ品質のサービスを提供します。',
    footer_desc: '国内多文化家庭の大学生のためのコミュニティ型インターンシップマッチング・職務教育統合プラットフォーム',
    footer_service: 'サービス', footer_support: 'サポート', footer_company: '会社',
    footer_community: 'コミュニティ', footer_education: '職務教育', footer_internship: 'インターンシップ',
    footer_faq: 'よくある質問', footer_help: 'カスタマーセンター', footer_notice: 'お知らせ',
    footer_about: '会社概要', footer_partner: 'パートナーシップ', footer_privacy: 'プライバシーポリシー',
    footer_copy: '多文化青年のより良い明日のために',
    board_title: 'コミュニティ', board_desc: '多文化青年が共にコミュニケーションし、情報を共有するスペースです。',
    tab_all: 'すべて', tab_notice: '📢 お知らせ', tab_community: '🤝 コミュニティ',
    tab_job: '💼 就職情報', tab_qna: '❓ Q&A',
    list_num: '番号', list_title: 'タイトル', list_author: '作成者', list_date: '日付', list_views: '閲覧',
    sort_latest: '新着順', sort_views: '閲覧数順', sort_popular: '人気順',
    write_title: '✏️ 投稿する', write_category: '掲示板を選択', write_input_title: 'タイトル',
    write_content: '内容', write_tag: 'タグ（任意）', write_tag_placeholder: '例: #インターンシップ #就職',
    write_placeholder: '内容を入力してください。お互いを尊重する温かいコミュニティを作りましょう 😊',
    cat_notice: 'お知らせ', cat_community: 'コミュニティ', cat_job: '就職情報', cat_qna: 'Q&A',
    side_latest: '最新のお知らせ', side_popular: '人気の投稿', side_tags: '人気タグ',
    toast_submitted: '投稿が登録されました！🎉',
    toast_title_required: 'タイトルを入力してください！', toast_content_required: '内容を入力してください！',
    no_posts: '投稿がありません',
    cat_community_opt: '🤝 コミュニティ', cat_job_opt: '💼 就職情報', cat_qna_opt: '❓ Q&A',
    edu_notice: '2026年雇用労働部「未来明日就労体験支援事業」参加者募集中',
    edu_title: '職務教育', edu_desc: '実務中心の教育で就職能力を高めましょう。国費支援コースから無料講義まで5言語で提供します。',
    edu_stat1: '48講座', edu_stat2: '6分野', edu_stat3: '無料', edu_stat4: '5言語対応',
    edu_filter_all: 'すべて', edu_filter_it: '💻 IT·開発', edu_filter_mkt: '📣 マーケティング',
    edu_filter_biz: '💼 経営·会計', edu_filter_data: '📊 データ分析',
    edu_filter_lang: '🗣️ 韓国語', edu_filter_design: '🎨 デザイン',
    edu_filter_beginner: '入門', edu_filter_intermediate: '中級',
    edu_gov_title: '🏛️ 2026年政府支援就職プログラム',
    edu_gov_desc: '雇用労働部・ソウル市などの公共機関と協力して実質的な就職支援を提供します。以下のプログラムはすべて無料で参加可能です。',
    edu_gov_btn: '申し込む',
    edu_featured: '🌟 おすすめ講座', edu_all_courses: '📚 全講座', edu_reviews: '💬 修了生の声',
    edu_enroll: '受講申し込み', edu_hours: '計24時間', edu_enrolled: '受講申し込みが完了しました！🎉',
    intern_notice: '2026年第1期雇用労働部「青年就労体験支援事業（インターン型）」— 参加企業募集締切 D-3',
    intern_title: 'インターンシップマッチング', intern_desc: 'AIがあなたの能力と関心を分析して最適なインターンシップを推薦します。',
    intern_stat1: '124件募集中', intern_stat2: '38社パートナー企業',
    intern_stat3: '89%就職連携率', intern_stat4: '平均月給200万ウォン',
    intern_ai_label: '✦ AIマッチングシステム',
    intern_ai_title: 'AIがぴったりのインターンシップを見つけます',
    intern_ai_desc: '教育修了履歴、関心分野、言語能力、居住地域を分析して最適なインターンシップ公告をマッチングします。',
    intern_ai_btn: 'AIマッチングを始める',
    intern_ai_toast: 'AIマッチングを開始します！しばらくお待ちください 🤖',
    intern_jobs: '📋 インターンシップ公告', intern_process: '📌 応募手順', intern_success: '🏆 合格体験談',
    intern_apply: '応募する', intern_applied: '応募しました！🎉',
    process1_title: 'プロフィール作成', process1_desc: '希望職務、言語能力、教育修了履歴などを入力します',
    process2_title: 'AIマッチング', process2_desc: 'AIがあなたの能力に合ったインターンシップを自動推薦します',
    process3_title: '簡単応募', process3_desc: 'ワンクリックで応募書類を提出して企業の連絡を待ちます',
    process4_title: '合格＆スタート', process4_desc: '面接準備から入社まで K-WorkBridge が一緒です',
  },

  vi: {
    nav_home: 'Trang chủ', nav_community: 'Cộng đồng', nav_education: 'Đào tạo',
    nav_internship: 'Thực tập', nav_login: 'Đăng nhập', nav_start: 'Bắt đầu miễn phí',
    free: 'Miễn phí', apply: 'Đăng ký', detail: 'Xem thêm →', all: 'Tất cả',
    new_post: '✏️ Viết bài', search_placeholder: 'Nhập từ khóa tìm kiếm',
    submit: 'Đăng bài', cancel: 'Hủy', latest: 'Mới nhất', views_sort: 'Xem nhiều nhất',
    hero_badge: 'Nền tảng việc làm cho thanh niên đa văn hóa',
    hero_h1_1: 'Từ Cộng đồng', hero_h1_2: 'đến Sự nghiệp',
    hero_sub: 'Kết nối thanh niên đa văn hóa với việc làm tại Hàn Quốc',
    hero_desc: 'K-WorkBridge là nền tảng kết hợp cộng đồng, đào tạo nghề và tuyển dụng thực tập sinh cho sinh viên đa văn hóa tại Hàn Quốc. Cùng nhau phát triển, cùng nhau thành công.',
    hero_btn1: 'Bắt đầu ngay', hero_btn2: 'Tìm hiểu thêm',
    stat1_num: '3 Bước', stat1_label: 'Hành trình nghề nghiệp',
    stat2_num: '5 Ngôn ngữ', stat2_label: 'Ngôn ngữ hỗ trợ',
    stat3_num: '100%', stat3_label: 'Dịch vụ miễn phí',
    flow1_title: 'Hoạt động Cộng đồng', flow1_desc: 'Xây dựng mạng lưới với các bạn trẻ có cùng hoàn cảnh, chia sẻ thông tin và cùng nhau phát triển.',
    flow2_title: 'Đào tạo Nghề', flow2_desc: 'Xây dựng năng lực cần thiết cho việc làm thông qua các chương trình đào tạo thực tế.',
    flow3_title: 'Kết nối Thực tập', flow3_desc: 'Hệ thống kết nối AI giúp bạn tìm kiếm cơ hội thực tập phù hợp nhất.',
    feat_label: 'Tính năng chính', feat_title: 'Tất cả cho sự nghiệp<br>của bạn',
    feat1_title: 'Mạng lưới Cộng đồng', feat1_desc: 'Không gian cộng đồng an toàn để thanh niên đa văn hóa kết nối và chia sẻ kinh nghiệm.',
    feat2_title: 'Đào tạo Nghề Tùy chỉnh', feat2_desc: 'Các khóa đào tạo thực tế về IT, marketing, quản lý bằng 5 ngôn ngữ.',
    feat3_title: 'Kết nối Thực tập AI', feat3_desc: 'Tự động kết nối bạn với cơ hội thực tập tốt nhất dựa trên kỹ năng và sở thích.',
    feat4_title: 'Hỗ trợ 5 Ngôn ngữ', feat4_desc: 'Tất cả dịch vụ có sẵn bằng tiếng Hàn, Anh, Trung, Nhật và Việt.',
    feat5_title: 'Hồ sơ & Portfolio', feat5_desc: 'Dễ dàng tạo hồ sơ và portfolio theo phong cách Hàn Quốc.',
    feat6_title: 'Hợp tác Doanh nghiệp', feat6_desc: 'Hợp tác với các công ty Hàn Quốc coi trọng đa dạng để cung cấp cơ hội việc làm.',
    how_label: 'Cách sử dụng', how_title: 'Hoàn thiện sự nghiệp trong 3 bước',
    how1_title: 'Tham gia Cộng đồng', how1_desc: 'Sau khi đăng ký, kết nối với những người trẻ có hoàn cảnh tương tự. Tham gia nhóm học tập, cố vấn và chia sẻ thông tin.',
    how2_title: 'Nâng cao Kỹ năng', how2_desc: 'Tham gia các khóa học IT, marketing, phân tích kinh doanh. Tất cả bài giảng đều bằng tiếng mẹ đẻ.',
    how3_title: 'Kết nối Thực tập', how3_desc: 'Sau khi hoàn thành đào tạo, AI đề xuất thực tập phù hợp. Kết nối với các công ty tôn trọng sự đa dạng.',
    cta_label: 'Bắt đầu ngay hôm nay', cta_title: 'Hành trình sự nghiệp<br>cùng K-WorkBridge',
    cta_desc: 'Đăng ký miễn phí và bắt đầu từ cộng đồng. Cùng nhau, chúng ta đi xa hơn và nhanh hơn.',
    cta_btn1: 'Bắt đầu miễn phí', cta_btn2: 'Liên hệ doanh nghiệp',
    lang_title: 'Bắt đầu bằng ngôn ngữ của bạn', lang_desc: 'Ngôn ngữ không nên là rào cản. K-WorkBridge cung cấp dịch vụ chất lượng như nhau bằng 5 ngôn ngữ.',
    footer_desc: 'Nền tảng kết nối thực tập và đào tạo nghề dựa trên cộng đồng cho sinh viên đa văn hóa tại Hàn Quốc',
    footer_service: 'Dịch vụ', footer_support: 'Hỗ trợ', footer_company: 'Công ty',
    footer_community: 'Cộng đồng', footer_education: 'Đào tạo', footer_internship: 'Thực tập',
    footer_faq: 'FAQ', footer_help: 'Trung tâm hỗ trợ', footer_notice: 'Thông báo',
    footer_about: 'Giới thiệu', footer_partner: 'Hợp tác', footer_privacy: 'Chính sách',
    footer_copy: 'Vì một ngày mai tươi sáng hơn cho thanh niên đa văn hóa',
    board_title: 'Cộng đồng', board_desc: 'Không gian để thanh niên đa văn hóa giao lưu và chia sẻ thông tin.',
    tab_all: 'Tất cả', tab_notice: '📢 Thông báo', tab_community: '🤝 Cộng đồng',
    tab_job: '💼 Việc làm', tab_qna: '❓ Hỏi đáp',
    list_num: 'STT', list_title: 'Tiêu đề', list_author: 'Tác giả', list_date: 'Ngày', list_views: 'Lượt xem',
    sort_latest: 'Mới nhất', sort_views: 'Xem nhiều', sort_popular: 'Phổ biến',
    write_title: '✏️ Viết bài', write_category: 'Chọn mục', write_input_title: 'Tiêu đề',
    write_content: 'Nội dung', write_tag: 'Thẻ (tùy chọn)', write_tag_placeholder: 'VD: #thực_tập #việc_làm',
    write_placeholder: 'Nhập nội dung. Hãy cùng xây dựng cộng đồng ấm áp 😊',
    cat_notice: 'Thông báo', cat_community: 'Cộng đồng', cat_job: 'Việc làm', cat_qna: 'Hỏi đáp',
    side_latest: 'Thông báo mới nhất', side_popular: 'Bài viết phổ biến', side_tags: 'Thẻ phổ biến',
    toast_submitted: 'Đã đăng bài thành công! 🎉',
    toast_title_required: 'Vui lòng nhập tiêu đề!', toast_content_required: 'Vui lòng nhập nội dung!',
    no_posts: 'Không có bài viết',
    cat_community_opt: '🤝 Cộng đồng', cat_job_opt: '💼 Việc làm', cat_qna_opt: '❓ Hỏi đáp',
    edu_notice: 'Đang tuyển sinh 「Chương trình hỗ trợ kinh nghiệm làm việc」của Bộ Lao động Hàn Quốc năm 2026',
    edu_title: 'Đào tạo Nghề', edu_desc: 'Nâng cao năng lực việc làm qua đào tạo thực tế. Từ khóa học có trợ cấp đến bài giảng miễn phí bằng 5 ngôn ngữ.',
    edu_stat1: '48 Khóa học', edu_stat2: '6 Lĩnh vực', edu_stat3: 'Miễn phí', edu_stat4: '5 Ngôn ngữ',
    edu_filter_all: 'Tất cả', edu_filter_it: '💻 IT·Lập trình', edu_filter_mkt: '📣 Marketing',
    edu_filter_biz: '💼 Quản trị', edu_filter_data: '📊 Phân tích dữ liệu',
    edu_filter_lang: '🗣️ Tiếng Hàn', edu_filter_design: '🎨 Thiết kế',
    edu_filter_beginner: 'Cơ bản', edu_filter_intermediate: 'Trung cấp',
    edu_gov_title: '🏛️ Chương trình hỗ trợ việc làm của chính phủ năm 2026',
    edu_gov_desc: 'Hợp tác với Bộ Lao động, Thành phố Seoul để cung cấp hỗ trợ việc làm thực chất. Tất cả chương trình dưới đây đều miễn phí.',
    edu_gov_btn: 'Đăng ký ngay',
    edu_featured: '🌟 Khóa học nổi bật', edu_all_courses: '📚 Tất cả khóa học', edu_reviews: '💬 Đánh giá học viên',
    edu_enroll: 'Đăng ký học', edu_hours: 'Tổng 24 giờ', edu_enrolled: 'Đăng ký thành công! 🎉',
    intern_notice: 'Đợt 1 năm 2026 「Chương trình thực tập hỗ trợ kinh nghiệm thanh niên」— Hạn đăng ký doanh nghiệp: còn D-3',
    intern_title: 'Kết nối Thực tập', intern_desc: 'AI phân tích năng lực và sở thích của bạn để đề xuất cơ hội thực tập tốt nhất.',
    intern_stat1: '124 Tin đang tuyển', intern_stat2: '38 Công ty đối tác',
    intern_stat3: '89% Tỷ lệ có việc', intern_stat4: 'Lương TB 2 triệu won/tháng',
    intern_ai_label: '✦ Hệ thống kết nối AI',
    intern_ai_title: 'AI tìm kiếm thực tập hoàn hảo cho bạn',
    intern_ai_desc: 'Phân tích lịch sử đào tạo, lĩnh vực quan tâm, ngôn ngữ và nơi ở để kết nối bạn với tin tuyển dụng tốt nhất.',
    intern_ai_btn: 'Bắt đầu kết nối AI',
    intern_ai_toast: 'Bắt đầu kết nối AI! Kết quả sẽ được gửi trong giây lát 🤖',
    intern_jobs: '📋 Tin tuyển dụng thực tập', intern_process: '📌 Quy trình đăng ký', intern_success: '🏆 Câu chuyện thành công',
    intern_apply: 'Ứng tuyển', intern_applied: 'Đã nộp hồ sơ! 🎉',
    process1_title: 'Hoàn thiện hồ sơ', process1_desc: 'Điền thông tin lĩnh vực quan tâm, ngôn ngữ và lịch sử đào tạo',
    process2_title: 'Kết nối AI', process2_desc: 'AI tự động đề xuất thực tập phù hợp với năng lực của bạn',
    process3_title: 'Nộp hồ sơ dễ dàng', process3_desc: 'Nộp hồ sơ một chạm và chờ phản hồi từ công ty',
    process4_title: 'Được nhận & Bắt đầu', process4_desc: 'K-WorkBridge đồng hành từ chuẩn bị phỏng vấn đến ngày đầu đi làm',
  }
};

// 현재 언어 가져오기 (localStorage 저장)
function getCurrentLang() {
  return localStorage.getItem('kwb_lang') || 'ko';
}

// 언어 설정
function setLang(lang) {
  localStorage.setItem('kwb_lang', lang);
  applyLang(lang);
  updateLangBtns(lang);
}

// 언어 버튼 업데이트
function updateLangBtns(lang) {
  document.querySelectorAll('.lang-btn').forEach(btn => {
    btn.classList.toggle('active', btn.dataset.lang === lang);
  });
}

// 번역 적용
function applyLang(lang) {
  const t = LANGS[lang] || LANGS.ko;
  document.querySelectorAll('[data-t]').forEach(el => {
    const key = el.dataset.t;
    if (t[key] !== undefined) {
      if (el.tagName === 'INPUT' || el.tagName === 'TEXTAREA') {
        el.placeholder = t[key];
      } else if (el.tagName === 'OPTION') {
        el.textContent = t[key];
      } else {
        el.innerHTML = t[key];
      }
    }
  });
  // 폰트 변경
  const fontMap = { ko: "'Noto Sans KR',sans-serif", en: "'Noto Sans KR',sans-serif", zh: "'Noto Sans SC','Noto Sans KR',sans-serif", ja: "'Noto Sans JP','Noto Sans KR',sans-serif", vi: "'Noto Sans KR',sans-serif" };
  document.body.style.fontFamily = fontMap[lang] || fontMap.ko;
}

// 페이지 로드 시 자동 적용
document.addEventListener('DOMContentLoaded', () => {
  const lang = getCurrentLang();
  applyLang(lang);
  updateLangBtns(lang);
});
